### ISSUE TITLE
Script to auto-generate contract interacts files 

### ISSUE THREAD

**Issue by deepesh-kn** [OpenST/organization-contracts#7]
Contract interacts creation in type-script has a lot of boilerplate code and its time consuming to maintain it manually. It will be helpful to consume APIs with proper typed parameters.

- Use `@0xproject/abi-gen` to generate contract interacts
(If you have a suggestion for the libraries that can be used, please suggest)
- Add NPM command to run the script e.g: `npm run generate`

**Comment by schemar** [comment]
Does `@0xproject/abi-gen` include TypeScript definition files like TypeChain?
Yes it does

**Comment by schemar** [comment]
This ticket is not about testing the generated code. This ticket is not about figuring out if we can swap the generated interacts into our existing tests. This ticket is about adding the tool and generating the contract interacts.

You should however *try* and see how it works what it does.

**Comment by 0xsarvesh** [comment]
I did POC on two approaches : 
1.  [0x@abi-gen](https://www.npmjs.com/package/@0x/abi-gen)
2. [typechain](https://www.npmjs.com/package/typechain) 

You can check POC code for 0x@abi-gen [here](https://github.com/sarvesh-ost/organization-contracts/tree/abi-gen_tool_0x) and POC code for typechain [here](https://github.com/sarvesh-ost/organization-contracts/tree/type_chain_example)

**Observation about `0x@abi-gen`**: Generation of contract interacts is very easy, it's a simple command.  

```
abi-gen --abis './build/contracts/*.json' --out './interacts/' --template 'node_modules/@0x/abi-gen-templates/contract.handlebars'  --partials 'node_modules/@0x/abi-gen-templates/partials/*.handlebars'
```
It also provide flexiblity of changing templates based on the requirement. However, utilization of interact is complex and requires many packages from 0x itself. for instance 
@0x/subproviders, @0x/contracts-gen,  @0x/web3-wrapper.  I tried deploying a contract with the generated interacts, but took me while to figure out inputs like artifact and supported provider. 
 
In my opinion, with this approach consumer of the interacts needs to have knowledge about @0x packages which is not very common. 

**Observation about `typechain `** : Generation of contract interacts is very easy, it's a simple command.  

```
ts-generator ts-generator.json
```
I tried deploying the `Organization` contract and making a transaction. It was very easy to adopt to this approach as this is very relatable with conventional web3. 

Interacts generated with this approach doesn't provide a mechanism to deploy contract so added a custom method to deploy.  

In my opinion, this approach is preferable to me because using interacts seems very easy and straight forward.

**Comment by 0xsarvesh** [comment]
@deepesh-kn @schemar  @benjaminbollen  @gulshanvasnani  @pgev  @jasonklein  what do you think?

**Comment by schemar** [comment]
Thanks for the analysis. I would vote for TypeChain. I have also seen it mentioned much more than the 0x tool.

So TypeChain only creates the definition files ("interfaces"), right? That's why there is no code, also no `deploy()`. However, we can nicely package it. We have the ABI and the interface now. So a consumer could easily deploy it with web3 and use the interface to make sure it is correct code.

Can you please check how TypeChain says you should deploy your contracts/create your contract interact instances to make use of their definitions? 🤔

**Comment by schemar** [comment]
In their example there is something about `createAndValidate()` 🧐

**Comment by schemar** [comment]
It seems you can just use the constructor of the generated classes?

**Comment by 0xsarvesh** [comment]
Yes,  I couldn't find anything about the deployment in the type chain. Even the example [here](https://github.com/ethereum-ts/TypeChain/pull/88/files#diff-540a9b8840419be93ddb8d4b53325637R8) has a seperate deployment function.

**Comment by deepesh-kn** [comment]
👍 We can go with TypeChain. It is simpler to use.

**Comment by abhayks1** [comment]
Reviewing this ticket

**Comment by abhayks1** [comment]
Just to point 👇 out in openst.js 0.9.4 release there was similar approach on generating interacts using abi through meta programming 📽. Later we moved away from the approach and started writing customised interacts. One advantage I remember 🎗that if a method implementation needs to be overridden(with customised implementation e.g. with added validations) it was possible.

**Reference**: 
https://github.com/OpenST/openst.js/blob/v0.9.4/lib/contractInteracts/generator.js
https://github.com/OpenST/openst.js/blob/v0.9.4/lib/contractInteracts/TokenHolder.js

**Comment by abhayks1** [comment]
@benjaminbollen @schemar @deepesh-kn @sarvesh-ost What do you think should we be exploring solutions(with TypeChain generator) to override or customize a contract interact method in case it's needed? I feel it's important as interacts also represents business logic 💼 👨‍💼
